SELECT 
    DISTINCT
    c.CAR_ID, 
    c.CAR_TYPE, 
    ROUND((c.DAILY_FEE * 30) * (1 - p.DISCOUNT_RATE / 100)) as FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE

WHERE 
    c.CAR_ID NOT IN (
        SELECT h.CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        WHERE h.START_DATE < '2022-12-01 00:00:00' 
        AND h.END_DATE >= '2022-11-01 00:00:00'
    )
    AND ((c.CAR_TYPE = '세단') or (c.CAR_TYPE = 'SUV'))
    AND p.DURATION_TYPE = '30일 이상'
    AND (ROUND((c.DAILY_FEE * 30) * (1 - p.DISCOUNT_RATE / 100)) >= 500000)
    AND (ROUND((c.DAILY_FEE * 30) * (1 - p.DISCOUNT_RATE / 100)) < 2000000)
    
ORDER BY
    FEE DESC,
    c.CAR_TYPE ASC,
    c.CAR_ID DESC