SELECT 
    p.PRODUCT_ID, 
    p.PRODUCT_NAME, 
    SUM(o.amount * p.price) as TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;